name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3  # Updated to use Node.js 20

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3  # Updated to use Node.js 20
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set Docker Image Tag
      run: echo "IMAGE_TAG=my-image-name-$(date +%s)" >> $GITHUB_ENV  # Changed colon to hyphen

    - name: Build and push Docker image
      run: |
        docker buildx build --push --tag ghcr.io/${{ github.repository }}:${{ env.IMAGE_TAG }} --file devops_essentials/Dockerfile .

